GET http://localhost:3002/user_management/?&sort=NORMAL&page_no=1&search=

###
POST  http://localhost:3002/user_management/
Content-Type: application/json

{
     "id": "1f86499d-d594-4605-9b06-8cf154059d8d",
    "name": "Panoti",
    "DOB": "2024-06-01",
    "contact_no": "123454321",
    "email": "panoti@gmai.com",
    "user_description": "I am Panoti"
}

###
PUT http://localhost:3002/user_management/1f86499d-d594-4605-9b06-8cf154059d8d
Content-Type: application/json


{
    "name": "Panoti",
    "DOB": "2024-06-01",
    "contact_no": "123454321",
    "email": "panoti@gmai.com",
    "user_description": "I am Pnoti"
}

###
DELETE http://localhost:3002/user_management/1f86499d-d594-4605-9b06-8cf154059d8d

### 


DELETE http://localhost:3002/user_management